CXX      = $(HOME)/.openmpi/bin/mpic++
INITSRC   = ../model/initialize
ESTSRC    = ../model/estimator
USRSRC    = ../model/usermodel
ISCL      = ../model/libscl/gpp
LSCL      = ../model/libscl/gpp
IMPI     = $(HOME)/.openmpi/include
LMPI     = $(HOME)/.openmpi/lib

CXXFLAGS  = -O2 -Wall -c -I$(INITSRC) -I$(USRSRC) -I$(ESTSRC) -I$(ISCL) -I$(IMPI)
LDFLAGS   = -L$(LMPI) -L$(LSCL) -lscl -lm

HEADERS  = $(ESTSRC)/estimator.h $(ESTSRC)/estimator_base.h \
	$(INITSRC)/initialize.h $(INITSRC)/pathname.h \
	$(ISCL)/libscl.h \
	$(USRSRC)/usermodel.h $(USRSRC)/sv_moments.h $(USRSRC)/sv_model.h

OBJECTS = initialize.o mcmc_class.o proposal.o asymptotics.o \
	usermodel.o sv_moments.o sv_model.o

LIBRARIES = libscl.a

PROGRAMS = bayes_gmm_mpi

all :  pathname.h $(LIBRARIES) $(PROGRAMS)

libscl.a :
	make -C $(LSCL)

bayes_gmm_mpi :  main_mpi.o $(OBJECTS) $(HEADERS) $(LIBRARIES)
	$(CXX) -o bayes_gmm_mpi main_mpi.o $(OBJECTS) $(LDFLAGS)
	rm -f *.o core core.*

pathname.h:
	echo "#define PATHNAME \"$(PWD)\"" > $(INITSRC)/pathname.h

main_mpi.o : $(INITSRC)/main_mpi.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(INITSRC)/main_mpi.cpp

initialize.o : $(INITSRC)/initialize.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(INITSRC)/initialize.cpp

mcmc_class.o : $(ESTSRC)/mcmc_class.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(ESTSRC)/mcmc_class.cpp

proposal.o : $(ESTSRC)/proposal.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(ESTSRC)/proposal.cpp

asymptotics.o : $(ESTSRC)/asymptotics.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(ESTSRC)/asymptotics.cpp

usermodel.o : $(USRSRC)/usermodel.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(USRSRC)/usermodel.cpp

sv_moments.o : $(USRSRC)/sv_moments.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(USRSRC)/sv_moments.cpp

sv_model.o : $(USRSRC)/sv_model.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) $(USRSRC)/sv_model.cpp


clean	:
	make -C $(LSCL) clean
	rm -f *.o core core.*

veryclean	:
	make -C $(LSCL) veryclean
	rm -f *.o core core.*
	rm -f $(PROGRAMS)

dirclean	:
	rm -f *.o core core.*
	rm -f $(PROGRAMS)
