all	: scltypes.gpp scltypes.ms scltypes.sun

scltypes.gpp : scltypes.tpl
	/bin/sh < ./scltypes.sh

scltypes.ms : scltypes.tpl
	/bin/sh < ./scltypes.sh

scltypes.sun : scltypes.tpl
	/bin/sh < ./scltypes.sh
